/** @type {import('tailwindcss').Config} */
import typography from "@tailwindcss/typography";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", "./src/styles/*.css"],
  safelist: [
    // Dynamically generated / JS-toggled classes that Tailwind purge must not remove
    "animate-marquee-left",
    "animate-marquee",
    "animate-shimmer",
    "animate-shimmer-slide",
    "animate-float",
    "animate-float-slow",
    "animate-bounce-subtle",
    "animate-pulse-subtle",
    "animate-pulse-ring",
    "animate-shake",
    "animate-morph",
    "glass",
    "glass-card",
    "glass-premium",
    "glass-dark",
    "glass-navbar",
    "glass-premium-dark",
    "text-gradient",
    "shimmer",
    "skeleton",
    "skeleton-enhanced",
    "skeleton-pulse",
    "shadow-tcs",
    "shadow-tcs-lg",
    "shadow-glow",
    "bottom-nav",
    "mobile-overlay",
    "mobile-drawer",
    "open",
  ],
  theme: {
    screens: {
      xs: "320px",
      xsm: "375px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      fontFamily: {
        sans: ["Segoe UI", "Inter", "sans-serif"],
        display: ["Inter", "Segoe UI", "sans-serif"],
      },
      colors: {
        // Brand palette — single source of truth (tokens.css aliases these via CSS vars; do not duplicate)
        brand: {
          start: "#667eea",
          end: "#764ba2",
          dark: "#5a67d8",
          light: "#e0e7ff",
          50: "#eef2ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          300: "#a5b4fc",
          400: "#818cf8",
          500: "#6366f1",
          600: "#667eea",
          700: "#5a67d8",
          800: "#4c51bf",
          900: "#4338ca",
        },
        surface: {
          DEFAULT: "#ffffff",
          secondary: "#f9fafb",
          tertiary: "#f3f4f6",
          dark: "#1f2937",
          "dark-secondary": "#374151",
        },
        success: {
          50: "#f0fdf4",
          100: "#dcfce7",
          400: "#4ade80",
          500: "#22c55e",
          600: "#16a34a",
        },
        warning: {
          50: "#fffbeb",
          100: "#fef3c7",
          400: "#fbbf24",
          500: "#f59e0b",
          600: "#d97706",
        },
        error: {
          50: "#fef2f2",
          100: "#fee2e2",
          400: "#f87171",
          500: "#ef4444",
          600: "#dc2626",
        },
      },
      spacing: {
        18: "4.5rem",
        88: "22rem",
        100: "25rem",
        120: "30rem",
      },
      boxShadow: {
        soft: "0 10px 30px rgba(0, 0, 0, 0.05)",
        glow: "0 5px 15px rgba(102, 126, 234, 0.4)",
        card: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
        "hover-card": "0 10px 25px rgba(0, 0, 0, 0.15)",
        elevated: "0 20px 40px rgba(0, 0, 0, 0.08)",
        "inner-soft": "inset 0 2px 4px rgba(0,0,0,0.05)",
      },
      borderRadius: {
        card: "20px",
        xs: "0.25rem",
        sm: "0.375rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "float-slow": "float-slow 20s ease-in-out infinite",
        "slide-up": "slide-up 0.6s ease-out forwards",
        "slide-in-right": "slide-in-right 0.5s ease-out forwards",
        "slide-in-up": "slide-in-up 0.5s ease-out forwards",
        "scale-in": "scale-in 0.5s ease-out forwards",
        "gradient-flow": "gradient-flow 15s ease infinite",
        shimmer: "shimmer 3s ease-in-out infinite",
        twinkle: "twinkle 2s ease-in-out infinite",
        "pulse-slow": "pulse-slow 4s ease-in-out infinite",
        "spin-slow": "spin-slow 30s linear infinite",
        "bounce-subtle": "bounce-subtle 2s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-20px) rotate(5deg)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(10px, -10px) scale(1.02)" },
          "66%": { transform: "translate(-5px, 5px) scale(0.98)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-up": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.8)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "gradient-flow": {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        shimmer: {
          "0%": { opacity: "0.3", transform: "scale(1)" },
          "50%": { opacity: "0.6", transform: "scale(1.1)" },
          "100%": { opacity: "0.3", transform: "scale(1)" },
        },
        twinkle: {
          "0%, 100%": { opacity: "0.2", transform: "scale(1)" },
          "50%": { opacity: "1", transform: "scale(1.5)" },
        },
        "pulse-slow": {
          "0%, 100%": { opacity: "0.2" },
          "50%": { opacity: "0.4" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
    },
  },
  plugins: [typography],
};
