/**
 * Application Error Codes
 * 
 * Centralized error code taxonomy for consistent error handling across
 * the application. Use these codes when throwing or returning errors
 * to ensure consistent error responses and client-side error handling.
 * 
 * Format: CATEGORY_SPECIFIC_ERROR
 * Example: AUTH_INVALID_TOKEN, DB_CONNECTION_FAILED, VALIDATION_MISSING_FIELD
 */

// Authentication & Authorization
export const AUTH_ERRORS = {
  INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  TWO_FACTOR_REQUIRED: 'AUTH_TWO_FACTOR_REQUIRED',
  TWO_FACTOR_INVALID: 'AUTH_TWO_FACTOR_INVALID',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  SESSION_INVALID: 'AUTH_SESSION_INVALID',
  OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  OTP_INVALID: 'AUTH_OTP_INVALID',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'AUTH_PHONE_NOT_VERIFIED',
  PASSWORD_RESET_EXPIRED: 'AUTH_PASSWORD_RESET_EXPIRED',
  INVALID_API_KEY: 'AUTH_INVALID_API_KEY',
  ADMIN_KEY_REQUIRED: 'AUTH_ADMIN_KEY_REQUIRED',
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
  ACCOUNT_LOCKOUT: 'AUTH_ACCOUNT_LOCKOUT',
}

// Database & Data
export const DB_ERRORS = {
  CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  QUERY_FAILED: 'DB_QUERY_FAILED',
  CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',
  UNIQUE_VIOLATION: 'DB_UNIQUE_VIOLATION',
  FOREIGN_KEY_VIOLATION: 'DB_FOREIGN_KEY_VIOLATION',
  NOT_FOUND: 'DB_NOT_FOUND',
  DUPLICATE_ENTRY: 'DB_DUPLICATE_ENTRY',
  MIGRATION_FAILED: 'DB_MIGRATION_FAILED',
  POOL_EXHAUSTED: 'DB_POOL_EXHAUSTED',
  TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED',
}

// Validation
export const VALIDATION_ERRORS = {
  MISSING_FIELD: 'VALIDATION_MISSING_FIELD',
  INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  INVALID_LENGTH: 'VALIDATION_INVALID_LENGTH',
  INVALID_VALUE: 'VALIDATION_INVALID_VALUE',
  INVALID_ENUM: 'VALIDATION_INVALID_ENUM',
  INVALID_DATE: 'VALIDATION_INVALID_DATE',
  INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  INVALID_PHONE: 'VALIDATION_INVALID_PHONE',
  INVALID_URL: 'VALIDATION_INVALID_URL',
  INVALID_FILE_TYPE: 'VALIDATION_INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'VALIDATION_FILE_TOO_LARGE',
  MISSING_REQUIRED: 'VALIDATION_MISSING_REQUIRED',
  INVALID_ARRAY: 'VALIDATION_INVALID_ARRAY',
  INVALID_NUMBER: 'VALIDATION_INVALID_NUMBER',
  INVALID_BOOLEAN: 'VALIDATION_INVALID_BOOLEAN',
}

// Business Logic
export const BUSINESS_ERRORS = {
  TEST_NOT_FOUND: 'BUSINESS_TEST_NOT_FOUND',
  TEST_NOT_AVAILABLE: 'BUSINESS_TEST_NOT_AVAILABLE',
  TEST_EXPIRED: 'BUSINESS_TEST_EXPIRED',
  TEST_ALREADY_SUBMITTED: 'BUSINESS_TEST_ALREADY_SUBMITTED',
  TEST_TIME_EXPIRED: 'BUSINESS_TEST_TIME_EXPIRED',
  SECTION_TIME_EXPIRED: 'BUSINESS_SECTION_TIME_EXPIRED',
  INSUFFICIENT_BALANCE: 'BUSINESS_INSUFFICIENT_BALANCE',
  PAYMENT_FAILED: 'BUSINESS_PAYMENT_FAILED',
  PAYMENT_PENDING: 'BUSINESS_PAYMENT_PENDING',
  SUBSCRIPTION_EXPIRED: 'BUSINESS_SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_REQUIRED: 'BUSINESS_SUBSCRIPTION_REQUIRED',
  ALREADY_ENROLLED: 'BUSINESS_ALREADY_ENROLLED',
  NOT_ENROLLED: 'BUSINESS_NOT_ENROLLED',
  EXAM_NOT_FOUND: 'BUSINESS_EXAM_NOT_FOUND',
  SERIES_NOT_FOUND: 'BUSINESS_SERIES_NOT_FOUND',
  QUESTION_NOT_FOUND: 'BUSINESS_QUESTION_NOT_FOUND',
  USER_NOT_FOUND: 'BUSINESS_USER_NOT_FOUND',
  CONTENT_NOT_FOUND: 'BUSINESS_CONTENT_NOT_FOUND',
}

// External Services
export const EXTERNAL_ERRORS = {
  S3_UPLOAD_FAILED: 'EXTERNAL_S3_UPLOAD_FAILED',
  S3_DOWNLOAD_FAILED: 'EXTERNAL_S3_DOWNLOAD_FAILED',
  EMAIL_SEND_FAILED: 'EXTERNAL_EMAIL_SEND_FAILED',
  SMS_SEND_FAILED: 'EXTERNAL_SMS_SEND_FAILED',
  PAYMENT_GATEWAY_ERROR: 'EXTERNAL_PAYMENT_GATEWAY_ERROR',
  REDIS_UNAVAILABLE: 'EXTERNAL_REDIS_UNAVAILABLE',
  SENTRY_ERROR: 'EXTERNAL_SENTRY_ERROR',
  AI_SERVICE_ERROR: 'EXTERNAL_AI_SERVICE_ERROR',
}

// System
export const SYSTEM_ERRORS = {
  INTERNAL_ERROR: 'SYSTEM_INTERNAL_ERROR',
  NOT_FOUND: 'SYSTEM_NOT_FOUND',
  METHOD_NOT_ALLOWED: 'SYSTEM_METHOD_NOT_ALLOWED',
  RATE_LIMIT_EXCEEDED: 'SYSTEM_RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE: 'SYSTEM_SERVICE_UNAVAILABLE',
  MAINTENANCE_MODE: 'SYSTEM_MAINTENANCE_MODE',
  FEATURE_DISABLED: 'SYSTEM_FEATURE_DISABLED',
  CONFIGURATION_ERROR: 'SYSTEM_CONFIGURATION_ERROR',
  DEPENDENCY_FAILED: 'SYSTEM_DEPENDENCY_FAILED',
  TIMEOUT: 'SYSTEM_TIMEOUT',
}

// Combine all error codes
export const ERROR_CODES = {
  ...AUTH_ERRORS,
  ...DB_ERRORS,
  ...VALIDATION_ERRORS,
  ...BUSINESS_ERRORS,
  ...EXTERNAL_ERRORS,
  ...SYSTEM_ERRORS,
}

// Error code to HTTP status mapping
export const ERROR_STATUS_MAP = {
  [AUTH_ERRORS.INVALID_TOKEN]: 401,
  [AUTH_ERRORS.TOKEN_EXPIRED]: 401,
  [AUTH_ERRORS.REFRESH_TOKEN_EXPIRED]: 401,
  [AUTH_ERRORS.INVALID_CREDENTIALS]: 401,
  [AUTH_ERRORS.ACCOUNT_LOCKED]: 423,
  [AUTH_ERRORS.ACCOUNT_DEACTIVATED]: 403,
  [AUTH_ERRORS.INSUFFICIENT_PERMISSIONS]: 403,
  [AUTH_ERRORS.TWO_FACTOR_REQUIRED]: 401,
  [AUTH_ERRORS.TWO_FACTOR_INVALID]: 401,
  [AUTH_ERRORS.SESSION_EXPIRED]: 401,
  [AUTH_ERRORS.SESSION_INVALID]: 401,
  [AUTH_ERRORS.OTP_EXPIRED]: 401,
  [AUTH_ERRORS.OTP_INVALID]: 401,
  [AUTH_ERRORS.EMAIL_NOT_VERIFIED]: 403,
  [AUTH_ERRORS.PHONE_NOT_VERIFIED]: 403,
  [AUTH_ERRORS.PASSWORD_RESET_EXPIRED]: 401,
  [AUTH_ERRORS.INVALID_API_KEY]: 401,
  [AUTH_ERRORS.ADMIN_KEY_REQUIRED]: 401,
  [AUTH_ERRORS.RATE_LIMITED]: 429,
  [AUTH_ERRORS.ACCOUNT_LOCKOUT]: 423,

  [DB_ERRORS.CONNECTION_FAILED]: 503,
  [DB_ERRORS.QUERY_FAILED]: 500,
  [DB_ERRORS.CONSTRAINT_VIOLATION]: 400,
  [DB_ERRORS.UNIQUE_VIOLATION]: 409,
  [DB_ERRORS.FOREIGN_KEY_VIOLATION]: 400,
  [DB_ERRORS.NOT_FOUND]: 404,
  [DB_ERRORS.DUPLICATE_ENTRY]: 409,
  [DB_ERRORS.MIGRATION_FAILED]: 500,
  [DB_ERRORS.POOL_EXHAUSTED]: 503,
  [DB_ERRORS.TRANSACTION_FAILED]: 500,

  [VALIDATION_ERRORS.MISSING_FIELD]: 400,
  [VALIDATION_ERRORS.INVALID_FORMAT]: 400,
  [VALIDATION_ERRORS.INVALID_LENGTH]: 400,
  [VALIDATION_ERRORS.INVALID_VALUE]: 400,
  [VALIDATION_ERRORS.INVALID_ENUM]: 400,
  [VALIDATION_ERRORS.INVALID_DATE]: 400,
  [VALIDATION_ERRORS.INVALID_EMAIL]: 400,
  [VALIDATION_ERRORS.INVALID_PHONE]: 400,
  [VALIDATION_ERRORS.INVALID_URL]: 400,
  [VALIDATION_ERRORS.INVALID_FILE_TYPE]: 400,
  [VALIDATION_ERRORS.FILE_TOO_LARGE]: 413,
  [VALIDATION_ERRORS.MISSING_REQUIRED]: 400,
  [VALIDATION_ERRORS.INVALID_ARRAY]: 400,
  [VALIDATION_ERRORS.INVALID_NUMBER]: 400,
  [VALIDATION_ERRORS.INVALID_BOOLEAN]: 400,

  [BUSINESS_ERRORS.TEST_NOT_FOUND]: 404,
  [BUSINESS_ERRORS.TEST_NOT_AVAILABLE]: 404,
  [BUSINESS_ERRORS.TEST_EXPIRED]: 410,
  [BUSINESS_ERRORS.TEST_ALREADY_SUBMITTED]: 409,
  [BUSINESS_ERRORS.TEST_TIME_EXPIRED]: 410,
  [BUSINESS_ERRORS.SECTION_TIME_EXPIRED]: 410,
  [BUSINESS_ERRORS.INSUFFICIENT_BALANCE]: 402,
  [BUSINESS_ERRORS.PAYMENT_FAILED]: 402,
  [BUSINESS_ERRORS.PAYMENT_PENDING]: 202,
  [BUSINESS_ERRORS.SUBSCRIPTION_EXPIRED]: 402,
  [BUSINESS_ERRORS.SUBSCRIPTION_REQUIRED]: 402,
  [BUSINESS_ERRORS.ALREADY_ENROLLED]: 409,
  [BUSINESS_ERRORS.NOT_ENROLLED]: 403,
  [BUSINESS_ERRORS.EXAM_NOT_FOUND]: 404,
  [BUSINESS_ERRORS.SERIES_NOT_FOUND]: 404,
  [BUSINESS_ERRORS.QUESTION_NOT_FOUND]: 404,
  [BUSINESS_ERRORS.USER_NOT_FOUND]: 404,
  [BUSINESS_ERRORS.CONTENT_NOT_FOUND]: 404,

  [EXTERNAL_ERRORS.S3_UPLOAD_FAILED]: 502,
  [EXTERNAL_ERRORS.S3_DOWNLOAD_FAILED]: 502,
  [EXTERNAL_ERRORS.EMAIL_SEND_FAILED]: 502,
  [EXTERNAL_ERRORS.SMS_SEND_FAILED]: 502,
  [EXTERNAL_ERRORS.PAYMENT_GATEWAY_ERROR]: 502,
  [EXTERNAL_ERRORS.REDIS_UNAVAILABLE]: 503,
  [EXTERNAL_ERRORS.SENTRY_ERROR]: 500,
  [EXTERNAL_ERRORS.AI_SERVICE_ERROR]: 502,

  [SYSTEM_ERRORS.INTERNAL_ERROR]: 500,
  [SYSTEM_ERRORS.NOT_FOUND]: 404,
  [SYSTEM_ERRORS.METHOD_NOT_ALLOWED]: 405,
  [SYSTEM_ERRORS.RATE_LIMIT_EXCEEDED]: 429,
  [SYSTEM_ERRORS.SERVICE_UNAVAILABLE]: 503,
  [SYSTEM_ERRORS.MAINTENANCE_MODE]: 503,
  [SYSTEM_ERRORS.FEATURE_DISABLED]: 404,
  [SYSTEM_ERRORS.CONFIGURATION_ERROR]: 500,
  [SYSTEM_ERRORS.DEPENDENCY_FAILED]: 503,
  [SYSTEM_ERRORS.TIMEOUT]: 504,
}

export default ERROR_CODES
