// Foreign-key relationship definitions for schema reconciliation.
// Used by PostgresHelpers.ensureForeignKey / reconcileRelationships.
export const RELATIONSHIP_DEFINITIONS = Object.freeze([
  {
    table: "assets",
    column: "uploaded_by",
    foreignTable: "users",
    foreignColumn: "id",
    constraintName: "assets_uploaded_by_fkey",
    onDelete: "SET NULL",
    indexName: "idx_assets_uploaded_by",
  },
  {
    table: "attempt_events",
    column: "attempt_id",
    foreignTable: "attempts",
    foreignColumn: "id",
    constraintName: "attempt_events_attempt_id_fkey",
    onDelete: "CASCADE",
  },
  {
    table: "attempt_events",
    column: "question_id",
    foreignTable: "questions",
    foreignColumn: "id",
    constraintName: "attempt_events_question_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_attempt_events_question_id",
  },
  {
    table: "attempt_answers",
    column: "attempt_id",
    foreignTable: "attempts",
    foreignColumn: "id",
    constraintName: "attempt_answers_attempt_id_fkey",
    onDelete: "CASCADE",
    dropIfMismatch: true,
    indexName: "idx_attempt_answers_attempt_id",
  },
  {
    table: "attempt_answers",
    column: "question_id",
    foreignTable: "questions",
    foreignColumn: "id",
    constraintName: "attempt_answers_question_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_attempt_answers_question_id",
  },
  {
    table: "attempts",
    column: "user_id",
    foreignTable: "users",
    foreignColumn: "id",
    constraintName: "attempts_user_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_attempts_user_id",
  },
  {
    table: "attempts",
    column: "test_id",
    foreignTable: "tests",
    foreignColumn: "id",
    constraintName: "attempts_test_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_attempts_test_id",
  },
  {
    table: "attempts",
    column: "series_id",
    foreignTable: "test_series",
    foreignColumn: "id",
    constraintName: "attempts_series_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_attempts_series_id",
  },
  {
    table: "banners",
    column: "asset_id",
    foreignTable: "assets",
    foreignColumn: "id",
    constraintName: "banners_asset_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_banners_asset_id",
  },
  {
    table: "bookmarks",
    column: "user_id",
    foreignTable: "users",
    foreignColumn: "id",
    constraintName: "bookmarks_user_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_bookmarks_user_id",
  },
  {
    table: "doubts",
    column: "user_id",
    foreignTable: "users",
    foreignColumn: "id",
    constraintName: "doubts_user_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_doubts_user_id",
  },
  {
    table: "doubt_replies",
    column: "user_id",
    foreignTable: "users",
    foreignColumn: "id",
    constraintName: "doubt_replies_user_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_doubt_replies_user_id",
  },
  {
    table: "promotions",
    column: "banner_asset_id",
    foreignTable: "assets",
    foreignColumn: "id",
    constraintName: "promotions_banner_asset_id_fkey",
    onDelete: "SET NULL",
  },
  {
    table: "questions",
    column: "chapter_id",
    foreignTable: "chapters",
    foreignColumn: "id",
    constraintName: "questions_chapter_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_questions_chapter_id",
  },
  {
    table: "questions",
    column: "image_asset_id",
    foreignTable: "assets",
    foreignColumn: "id",
    constraintName: "questions_image_asset_id_fkey",
    onDelete: "SET NULL",
  },
  {
    table: "study_group_members",
    column: "user_id",
    foreignTable: "users",
    foreignColumn: "id",
    constraintName: "study_group_members_user_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_study_group_members_user_id",
  },
  {
    table: "study_groups",
    column: "user_id",
    foreignTable: "users",
    foreignColumn: "id",
    constraintName: "study_groups_user_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_study_groups_user_id",
  },
  {
    table: "subscriptions",
    column: "user_id",
    foreignTable: "users",
    foreignColumn: "id",
    constraintName: "subscriptions_user_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_subscriptions_user_id",
  },
  // test_attempts is a VIEW (migration 039/048), not a table — FK constraints
  // belong on the underlying "attempts" table. Skipping to avoid
  // "ALTER action ADD CONSTRAINT cannot be performed on relation" errors.
  {
    table: "test_categories",
    column: "exam_category_id",
    foreignTable: "exam_categories",
    foreignColumn: "category_id",
    constraintName: "test_categories_exam_category_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_test_categories_exam_category_id",
  },
  {
    table: "tests",
    column: "banner_asset_id",
    foreignTable: "assets",
    foreignColumn: "id",
    constraintName: "tests_banner_asset_id_fkey",
    onDelete: "SET NULL",
  },
  {
    table: "tests",
    column: "promotion_banner_asset_id",
    foreignTable: "assets",
    foreignColumn: "id",
    constraintName: "tests_promotion_banner_asset_id_fkey",
    onDelete: "SET NULL",
  },
  {
    table: "test_questions",
    column: "test_id",
    foreignTable: "tests",
    foreignColumn: "id",
    constraintName: "test_questions_test_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_test_questions_test_id",
  },
  {
    table: "test_questions",
    column: "question_id",
    foreignTable: "questions",
    foreignColumn: "id",
    constraintName: "test_questions_question_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_test_questions_question_id",
  },
  {
    table: "tests",
    column: "subject_id",
    foreignTable: "subjects",
    foreignColumn: "id",
    constraintName: "tests_subject_id_fkey",
    onDelete: "SET NULL",
    dropIfMismatch: true,
  },
  {
    table: "user_achievements",
    column: "user_id",
    foreignTable: "users",
    foreignColumn: "id",
    constraintName: "user_achievements_user_id_fkey",
    onDelete: "CASCADE",
  },
  {
    table: "tests",
    column: "series_id",
    foreignTable: "test_series",
    foreignColumn: "id",
    constraintName: "tests_series_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_tests_series_id",
  },
  {
    table: "tests",
    column: "stage_id",
    foreignTable: "stages",
    foreignColumn: "id",
    constraintName: "tests_stage_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_tests_stage_id",
  },
  {
    table: "subject_parts",
    column: "subject_id",
    foreignTable: "subjects",
    foreignColumn: "id",
    constraintName: "subject_parts_subject_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_subject_parts_subject_id",
  },
  {
    table: "units",
    column: "part_id",
    foreignTable: "subject_parts",
    foreignColumn: "id",
    constraintName: "units_part_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_units_part_id",
  },
  {
    table: "chapters",
    column: "unit_id",
    foreignTable: "units",
    foreignColumn: "id",
    constraintName: "chapters_unit_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_chapters_unit_id",
  },
  {
    table: "topics",
    column: "chapter_id",
    foreignTable: "chapters",
    foreignColumn: "id",
    constraintName: "topics_chapter_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_topics_chapter_id",
  },
  {
    table: "subtopics",
    column: "topic_id",
    foreignTable: "topics",
    foreignColumn: "id",
    constraintName: "subtopics_topic_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_subtopics_topic_id",
  },
  {
    table: "subjects",
    column: "parent_id",
    foreignTable: "subjects",
    foreignColumn: "id",
    constraintName: "subjects_parent_id_fkey",
    onDelete: "CASCADE",
    indexName: "idx_subjects_parent_id",
  },
  {
    table: "test_sections",
    column: "category_id",
    foreignTable: "test_categories",
    foreignColumn: "id",
    constraintName: "test_sections_category_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_test_sections_category",
  },
  {
    table: "tests",
    column: "section_id",
    foreignTable: "test_sections",
    foreignColumn: "id",
    constraintName: "tests_section_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_tests_section_id",
  },
  {
    table: "test_questions",
    column: "section_id",
    foreignTable: "test_sections",
    foreignColumn: "id",
    constraintName: "test_questions_section_id_fkey",
    onDelete: "SET NULL",
    indexName: "idx_test_questions_section_id",
  },
]);
